### ISSUE TITLE
Add Roxygen comments 

### ISSUE THREAD

**Issue by jkbest2** [cbedwards-dfw/namespacify#2]
If I remember correctly, even when you use `package::function`, you still need to include something like `##' @importFrom package function` so that Roxygen knows to include it in the `NAMESPACE` file. The `usethis::use_import_from` function (looks like you're already using this) would make this pretty easy. I'm not sure if it checks for redundant declarations.

**Comment by cbedwards-dfw** [comment]
I think the usethis functions generally check for redundancy, so we're good on that front. 

TBH I've typically just been using `usethis::use_package()`. I like the idea of semi-automating this as well -- I'm thinking I'll fold some informative `cli()` text into the upcoming `detect_packages()` function, to recommend the user add the packages to namespace. And maybe use {clipr} to copy the suggested function calls to the clipboard.

**Comment by cbedwards-dfw** [comment]
@jkbest2, let me know how the new solution looks to you. You can test it by running package_detect() providing the path to an R script as the `folder` argument.
